<script>

<div id="orders">
    <!-- This HTML should be dynamically generated by JS -->
    <article>
        <h3>Order #x</h3>
        <dl>
            <dt>Item Ordered</dt>
            <dd>Such and such item</dd>
            <dt>Ordered by</dt>
            <dd>Ordered by such and such</dd>
        </dl>
    </article>
</div>
</script>